[package]
name = "rq"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
serde_json = "1.0.140"
serde_merge = "0.1.3"
sqlparser = { version = "0.56.0", features = ["std", "recursive-protection", "serde", "serde_json"] }
